-- AUTO-GENERATED by directus/gen-content-seed.mjs — do not edit by hand.
-- Seeds the UI languages and the legal pages (English). Run FIRST.
BEGIN;

-- Languages (Directus translations collection).
INSERT INTO languages (code, name, sort) VALUES ('it', 'Italiano', 0) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort = EXCLUDED.sort;
INSERT INTO languages (code, name, sort) VALUES ('en', 'English', 1) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort = EXCLUDED.sort;
INSERT INTO languages (code, name, sort) VALUES ('es', 'Español', 2) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort = EXCLUDED.sort;
INSERT INTO languages (code, name, sort) VALUES ('fr', 'Français', 3) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort = EXCLUDED.sort;
INSERT INTO languages (code, name, sort) VALUES ('de', 'Deutsch', 4) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort = EXCLUDED.sort;
INSERT INTO languages (code, name, sort) VALUES ('pt', 'Português', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort = EXCLUDED.sort;
INSERT INTO languages (code, name, sort) VALUES ('ja', '日本語', 6) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort = EXCLUDED.sort;
INSERT INTO languages (code, name, sort) VALUES ('zh', '中文', 7) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort = EXCLUDED.sort;

-- Legal pages + English body (markdown).
INSERT INTO legal_pages (slug, version) VALUES ('terms', '2026-06-10') ON CONFLICT (slug) DO UPDATE SET version = EXCLUDED.version;
INSERT INTO legal_translations (page_id, language, title, body)
  SELECT id, 'en', 'Terms of Service', '> ⚠️ **Draft template — not legal advice.** Review with a qualified lawyer before relying on it.

Welcome to VoxTranslate ("the Service"), a real-time translated video-calling application. These Terms of Service ("Terms") govern your access to and use of the Service. By creating an account, signing in, or otherwise using the Service, you agree to these Terms. If you do not agree, do not use the Service.

## 1. Eligibility

You must be at least 18 years old to use the Service. By using it you represent that you are 18 or older and have the legal capacity to enter into these Terms. The Service is not directed to children, and we do not knowingly collect personal data from anyone under 18.

## 2. Accounts

Some features require an account, which you create by signing in with Google. You are responsible for activity under your account and for keeping your credentials secure. You may use the Service as a guest where permitted; guest access may be limited (for example, a time cap or being restricted to private rooms).

## 3. Acceptable use

Your use of the Service is subject to our Acceptable Use Policy, which is incorporated into these Terms. In short: do not use the Service to harass, abuse, threaten, or harm others; do not transmit illegal, hateful, or sexually exploitative content; and do not attempt to disrupt or compromise the Service.

## 4. Credits, billing and refunds

- Paid features are metered in credits, purchased through our payment processor (Stripe) and deducted as you use metered features such as transcribed and translated speaking time.
- Prices and package contents are shown at the time of purchase. Credits have no cash value, are non-transferable, and — except where required by law — are non-refundable once consumed.
- You are responsible for any taxes associated with your purchases unless stated otherwise at checkout.

## 5. Content and moderation

You are solely responsible for the audio, video, and text you transmit. To keep the Service safe, we apply automated content filtering to transcribed speech and chat, and provide tools to report and block participants. We may suspend or terminate accounts, remove content, or restrict access where we reasonably believe these Terms or the Acceptable Use Policy have been violated.

## 6. Privacy

Our Privacy Policy explains what data we process and why. By using the Service you acknowledge that audio is processed in real time to provide transcription and translation, as described there.

## 7. Service availability

The Service is provided on an "as is" and "as available" basis. We do not guarantee that it will be uninterrupted, secure, or error-free, and we may modify, suspend, or discontinue features at any time.

## 8. Disclaimers and limitation of liability

To the maximum extent permitted by law, the Service is provided without warranties of any kind, and we are not liable for any indirect, incidental, or consequential damages, or for translation inaccuracies. Nothing in these Terms limits liability that cannot be limited under applicable law, including your statutory rights as a consumer.

## 9. Termination

You may stop using the Service and delete your account at any time. We may suspend or terminate your access if you violate these Terms. Provisions that by their nature should survive termination will survive.

## 10. Changes to these Terms

We may update these Terms from time to time. When we make material changes, we will update the version and date and, where appropriate, ask you to accept the updated Terms before continuing to use the Service.

## 11. Contact

Questions about these Terms? Contact us at support@voxtranslate.app.' FROM legal_pages WHERE slug = 'terms'
  ON CONFLICT (page_id, language) DO UPDATE SET title = EXCLUDED.title, body = EXCLUDED.body;
INSERT INTO legal_pages (slug, version) VALUES ('privacy', '2026-06-10') ON CONFLICT (slug) DO UPDATE SET version = EXCLUDED.version;
INSERT INTO legal_translations (page_id, language, title, body)
  SELECT id, 'en', 'Privacy Policy', '> ⚠️ **Draft template — not legal advice.** Review with a qualified lawyer before relying on it.

This Privacy Policy explains what personal data VoxTranslate ("we", "us") processes when you use our real-time translated video-calling service, why we process it, and the rights you have. It is written with the EU General Data Protection Regulation (GDPR) and similar laws in mind.

## 1. Who is the data controller

VoxTranslate is the controller for personal data processed through the Service. For any privacy request, contact privacy@voxtranslate.app. *(Replace with your registered legal entity name, address, and — if applicable — your EU/UK representative and Data Protection Officer.)*

## 2. What data we process

- **Account data** — when you sign in with Google, we receive your name, email address, and profile picture URL.
- **Audio (transient)** — while you speak, your microphone audio is streamed to our speech-to-text provider to generate a live transcript. We do not store raw audio.
- **Transcripts & translations (transient)** — generated to display subtitles and translated text to other participants. Relayed in real time and not retained after the call, except where included in an abuse report.
- **Chat messages** — relayed and translated between participants during a call.
- **Usage & billing data** — credit balance, transactions, and per-session speaking time used to meter and bill the Service.
- **Safety data** — abuse reports you submit or that are submitted about you (which may include a short transcript excerpt), and moderation/ban records.
- **Technical data** — basic connection metadata needed to operate the real-time service and keep it secure.

Video and audio between participants are sent peer-to-peer (WebRTC) and are not routed through or recorded by our servers. Our server handles signaling, the live speech-to-text stream, translation, and chat relay.

## 3. Why we process it and our legal bases

- Provide the call, transcription and translation — performance of a contract.
- Process the audio needed for live captions/translation — contract; and your consent given at sign-up.
- Metering, billing and fraud prevention — contract; legitimate interests.
- Safety, moderation and handling abuse reports — legitimate interests in a safe service; legal obligation.
- Keeping legally required transaction records — legal obligation.

## 4. Service providers (processors / sub-processors)

We share personal data with the providers below strictly to operate the Service. Some are located outside the EEA; where that is the case we rely on appropriate safeguards such as the EU Standard Contractual Clauses.

- **Google** — sign-in (OAuth): name, email, profile picture.
- **Deepgram** — speech-to-text: streamed audio (transient).
- **Groq** — machine translation: transcript text (transient).
- **Stripe** — payment processing: billing details, payment data.
- **Supabase** — database / account & billing storage: account, usage, billing, safety data.
- **Vercel** — frontend hosting: technical/connection data.
- **Railway** — backend hosting: technical/connection data.

*(Confirm each provider''s current role, region, and safeguards before publishing, and keep this list up to date.)*

## 5. How long we keep data

- **Audio, transcripts and translations:** processed in real time and not stored after the call.
- **Account data:** kept while your account exists; deleted when you delete your account.
- **Billing/transaction records:** retained as required by applicable tax and accounting laws.
- **Safety/abuse reports and ban records:** retained for as long as needed to keep the Service safe and to comply with legal obligations.

## 6. Your rights

Subject to applicable law, you have the right to access, rectify, and erase your data; to receive it in a portable format; to restrict or object to certain processing; to withdraw consent at any time; and to lodge a complaint with your local data protection authority. You can exercise access/portability with **Download my data** and erasure with **Delete my account** in the Privacy & data panel inside the app, or email privacy@voxtranslate.app.

## 7. Security

We use industry-standard measures to protect personal data, including encryption in transit and peer-to-peer media that does not transit our servers. No method of transmission or storage is completely secure, however, and we cannot guarantee absolute security.

## 8. Children

The Service is for adults (18+). We do not knowingly process data of children. If you believe a child has provided us data, contact us and we will delete it.

## 9. Changes

We may update this Policy; we will revise the version and date and, for material changes, take additional steps where required by law.' FROM legal_pages WHERE slug = 'privacy'
  ON CONFLICT (page_id, language) DO UPDATE SET title = EXCLUDED.title, body = EXCLUDED.body;
INSERT INTO legal_pages (slug, version) VALUES ('acceptable-use', '2026-06-10') ON CONFLICT (slug) DO UPDATE SET version = EXCLUDED.version;
INSERT INTO legal_translations (page_id, language, title, body)
  SELECT id, 'en', 'Acceptable Use Policy', '> ⚠️ **Draft template — not legal advice.** Review with a qualified lawyer before relying on it.

This Acceptable Use Policy ("AUP") sets out the rules for using VoxTranslate. It is part of our Terms of Service. By using the Service you agree to follow this AUP. We may suspend or terminate accounts, remove content, or restrict access for violations.

## 1. Be respectful to other participants

You may not use the Service to:

- harass, bully, threaten, stalk, or intimidate anyone;
- post or transmit hateful content, or attack people based on race, ethnicity, national origin, religion, sex, gender, sexual orientation, disability, or any other protected characteristic;
- share sexually explicit or sexually exploitative content, or solicit such content;
- expose others to graphic violence or content intended to shock or disgust.

## 2. No illegal or harmful activity

- Do not use the Service for any unlawful purpose or to facilitate illegal activity.
- Do not engage in fraud, scams, phishing, or impersonation of any person or organization.
- Do not share content that infringes others'' intellectual property or privacy rights.
- Absolutely no content that sexually exploits or endangers minors. We report such content to the relevant authorities.

## 3. No spam or abuse of the platform

- Do not send spam, bulk unsolicited messages, or advertisements.
- Do not attempt to gain unauthorized access to accounts, rooms, systems, or data.
- Do not probe, scan, overload, disrupt, or otherwise interfere with the Service or its security features.
- Do not use bots, scrapers, or automated means to access the Service except as expressly permitted.

## 4. Recording and consent

Respect the privacy of others. Do not record, screenshot, or redistribute calls, audio, video, transcripts, or translations without the consent of the people involved and as required by the laws that apply to you.

## 5. Reporting and enforcement

Each participant can be reported or blocked from within a call. We use automated filtering on transcribed speech and chat to detect severe content, and we review reports. Depending on severity, we may issue warnings, temporarily suspend, or permanently ban accounts. Serious violations may be reported to law enforcement.

## 6. Contact

To report abuse or ask about this policy, use the in-app report tools or email abuse@voxtranslate.app.' FROM legal_pages WHERE slug = 'acceptable-use'
  ON CONFLICT (page_id, language) DO UPDATE SET title = EXCLUDED.title, body = EXCLUDED.body;
COMMIT;
