-- Transcript persistence (spec 0009): one call_sessions row per room lifetime,
-- its participants, and the speech/chat events captured during the call.
-- Recording happens only when the database is configured; sessions in which no
-- signed-in user took part are purged on finalize (nobody could download them).

CREATE TABLE IF NOT EXISTS call_sessions (
    id         UUID PRIMARY KEY,   -- generated by RoomManager (room-lifetime id)
    room       TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at   TIMESTAMPTZ
);

-- Who was in the call. `user_id` is NULL for guests; ON DELETE CASCADE erases
-- the row (name is PII) when the account is deleted (GDPR).
CREATE TABLE IF NOT EXISTS session_participants (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES call_sessions(id) ON DELETE CASCADE,
    peer_id    TEXT NOT NULL,
    user_id    UUID REFERENCES users(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    lang       TEXT NOT NULL,
    joined_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    left_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_session_participants_session
    ON session_participants (session_id);
CREATE INDEX IF NOT EXISTS idx_session_participants_user_joined
    ON session_participants (user_id, joined_at DESC);

-- One row per finalized speech transcript or chat message. `translations` is
-- the full fan-out map { lang: text }. `speaker_user_id` cascades on account
-- deletion so a user's utterances disappear with their account (GDPR); `ts` is
-- when the words were spoken/sent (capture time), `created_at` when the batch
-- insert landed.
CREATE TABLE IF NOT EXISTS transcript_events (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id      UUID NOT NULL REFERENCES call_sessions(id) ON DELETE CASCADE,
    event_type      TEXT NOT NULL CHECK (event_type IN ('speech', 'chat')),
    speaker_peer_id TEXT NOT NULL,
    speaker_user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    speaker_name    TEXT NOT NULL,
    original_text   TEXT NOT NULL,
    original_lang   TEXT NOT NULL,
    translations    JSONB NOT NULL DEFAULT '{}'::jsonb,
    ts              TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_transcript_events_session_ts
    ON transcript_events (session_id, ts);
